// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3TXFNAKIXCeMnN_yunANzwgQ0wB6od6w',
    appId: '1:521942787829:web:dabf8c7b63ab06292387bc',
    messagingSenderId: '521942787829',
    projectId: 'harsh-bookhub',
    authDomain: 'harsh-bookhub.firebaseapp.com',
    storageBucket: 'harsh-bookhub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9FxCfQ-LVetrrKG8DclS9JblTTZAqczI',
    appId: '1:521942787829:android:80543ed5c18af9232387bc',
    messagingSenderId: '521942787829',
    projectId: 'harsh-bookhub',
    storageBucket: 'harsh-bookhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_QkoQyie-fuuCt4MNBW2YNBr9RRLEEBY',
    appId: '1:521942787829:ios:1ec317a353b44b9b2387bc',
    messagingSenderId: '521942787829',
    projectId: 'harsh-bookhub',
    storageBucket: 'harsh-bookhub.firebasestorage.app',
    iosBundleId: 'com.example.bookhubApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_QkoQyie-fuuCt4MNBW2YNBr9RRLEEBY',
    appId: '1:521942787829:ios:1ec317a353b44b9b2387bc',
    messagingSenderId: '521942787829',
    projectId: 'harsh-bookhub',
    storageBucket: 'harsh-bookhub.firebasestorage.app',
    iosBundleId: 'com.example.bookhubApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3TXFNAKIXCeMnN_yunANzwgQ0wB6od6w',
    appId: '1:521942787829:web:5b08f092931fabaa2387bc',
    messagingSenderId: '521942787829',
    projectId: 'harsh-bookhub',
    authDomain: 'harsh-bookhub.firebaseapp.com',
    storageBucket: 'harsh-bookhub.firebasestorage.app',
  );
}
